#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : setxkbmap
Version  : 1.3.2
Release  : 4
URL      : https://www.x.org/releases/individual/app/setxkbmap-1.3.2.tar.bz2
Source0  : https://www.x.org/releases/individual/app/setxkbmap-1.3.2.tar.bz2
Source1  : https://www.x.org/releases/individual/app/setxkbmap-1.3.2.tar.bz2.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : HPND
Requires: setxkbmap-bin = %{version}-%{release}
Requires: setxkbmap-license = %{version}-%{release}
Requires: setxkbmap-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xkbfile)
BuildRequires : pkgconfig(xorg-macros)

%description
setxkbmap is an X11 client to change the keymaps in the X server for a
specified keyboard to use the layout determined by the options listed
on the command line.

%package bin
Summary: bin components for the setxkbmap package.
Group: Binaries
Requires: setxkbmap-license = %{version}-%{release}

%description bin
bin components for the setxkbmap package.


%package license
Summary: license components for the setxkbmap package.
Group: Default

%description license
license components for the setxkbmap package.


%package man
Summary: man components for the setxkbmap package.
Group: Default

%description man
man components for the setxkbmap package.


%prep
%setup -q -n setxkbmap-1.3.2
cd %{_builddir}/setxkbmap-1.3.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604360689
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604360689
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/setxkbmap
cp %{_builddir}/setxkbmap-1.3.2/COPYING %{buildroot}/usr/share/package-licenses/setxkbmap/9c19301d4230a125288f4b870dd634e3fe984110
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/setxkbmap

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/setxkbmap/9c19301d4230a125288f4b870dd634e3fe984110

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/setxkbmap.1
