#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0xE23B7E70B467F0BF (office@who-t.net)
#
Name     : setxkbmap
Version  : 1.3.4
Release  : 6
URL      : https://www.x.org/releases/individual/app/setxkbmap-1.3.4.tar.xz
Source0  : https://www.x.org/releases/individual/app/setxkbmap-1.3.4.tar.xz
Source1  : https://www.x.org/releases/individual/app/setxkbmap-1.3.4.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : HPND
Requires: setxkbmap-bin = %{version}-%{release}
Requires: setxkbmap-license = %{version}-%{release}
Requires: setxkbmap-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xkbfile)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xrandr)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
setxkbmap is an X11 client to change the keymaps in the X server for a
specified keyboard to use the layout determined by the options listed
on the command line.

%package bin
Summary: bin components for the setxkbmap package.
Group: Binaries
Requires: setxkbmap-license = %{version}-%{release}

%description bin
bin components for the setxkbmap package.


%package license
Summary: license components for the setxkbmap package.
Group: Default

%description license
license components for the setxkbmap package.


%package man
Summary: man components for the setxkbmap package.
Group: Default

%description man
man components for the setxkbmap package.


%prep
%setup -q -n setxkbmap-1.3.4
cd %{_builddir}/setxkbmap-1.3.4
pushd ..
cp -a setxkbmap-1.3.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1688746693
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1688746693
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/setxkbmap
cp %{_builddir}/setxkbmap-%{version}/COPYING %{buildroot}/usr/share/package-licenses/setxkbmap/9c19301d4230a125288f4b870dd634e3fe984110 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/setxkbmap
/usr/bin/setxkbmap

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/setxkbmap/9c19301d4230a125288f4b870dd634e3fe984110

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/setxkbmap.1
